name: "HA ngrok"
version: "1.0.2"
slug: "ngrok"
description: "Expose your Home Assistant instance to the internet using ngrok."
url: "https://github.com/yourusername/hangrok"
startup: "services"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - config:rw
panel_icon: "mdi:home-export-outline"
options:
  auth_token: ""
schema:
  auth_token: str
