name: "HA ngrok"
version: "1.0.14"
slug: "ngrok"
description: "Expose your Home Assistant instance to the internet using ngrok."
url: "https://github.com/yourusername/hangrok"
startup: "services"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - config:rw
ingress: true
ingress_port: 4040
panel_icon: "mdi:home-export-outline"
options:
  host: "homeassistant"
  auth_token: ""
  region: ""
  domain: ""
schema:
  host: str
  auth_token: str
  region: list(us|eu|ap|au|sa|jp|in)?
  domain: str?
